### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by frankzen** [lanurmi/efte#103]
Where does efte look for config files? I put a copy into $HOME/.config/efte but it is ignored. Should it be somewhere else ?
I am on Linux Mint 18.1
Thanks

**Comment by lanurmi** [comment]
When you execute the `efte` binary on command line, it will output a list of paths where it looks for config files. $HOME/.config/efte is not on this list.

**Comment by frankzen** [comment]
Not in the version Mint supplies. With the command line efte -v it outputs all the files it is loading but the only path is /usr/share/efte. It doesn't appear to look anywhere else.

**Comment by frankzen** [comment]
like this:
frank@ThinkCentre ~ $ efte -v
[define     ] OS_UNIX
found: /usr/share/efte/config/mymain.fte
[include    ] systemmain.fte... found: /usr/share/efte/config/systemmain.fte
[include    ] main.fte... found: /usr/share/efte/config/main.fte
[define     ] UI_FTE
[define     ] 1TBS_BRACE
[define     ] COLORS_BLUEZ_BG
[define     ] GUI_X11
[include    ] global.fte... found: /usr/share/efte/config/global.fte
[include    ] pal_base.fte... found: /usr/share/efte/config/pal_base.fte
[include    ] pal_bluez.fte... found: /usr/share/efte/config/pal_bluez.fte
[include    ] color.fte... found: /usr/share/efte/config/color.fte
[include    ] m_plain.fte... found: /usr/share/efte/config/m_plain.fte
[include    ] m_source.fte... found: /usr/share/efte/config/m_source.fte
[include    ] m_markup.fte... found: /usr/share/efte/config/m_markup.fte
[include    ] m_4gl.fte... found: /usr/share/efte/config/m_4gl.fte
[include    ] m_a51.fte... found: /usr/share/efte/config/m_a51.fte
[include    ] m_ada.fte... found: /usr/share/efte/config/m_ada.fte
[include    ] m_asm.fte... found: /usr/share/efte/config/m_asm.fte
[include    ] m_asm370.fte... found: /usr/share/efte/config/m_asm370.fte
[include    ] m_basic.fte... found: /usr/share/efte/config/m_basic.fte
[include    ] m_bin.fte... found: /usr/share/efte/config/m_bin.fte
[include    ] m_c.fte... found: /usr/share/efte/config/m_c.fte
[include    ] m_catbs.fte... found: /usr/share/efte/config/m_catbs.fte
[include    ] m_clario.fte... found: /usr/share/efte/config/m_clario.fte

**Comment by lanurmi** [comment]
Well, I didn't even know Mint supplies efte, and it certainly isn't packaged by me, so I cannot take responsibility for what it does. If the same problem can be reproduced with binaries compiled from Github master, then I can have a further look.

**Comment by frankzen** [comment]
I DL the zip file, ran cmake and make, make install. Binaries ended up in

/usr/local/bin and other associated files in /usr/local. The binary acts 
exactly the same,

seemingly ignoring any config files other than /usr/local/share/efte/

BTW, the readme file refers users to the wiki for installation 
instructions and

there are none there..the wiki is empty.
