### ISSUE TITLE
Backspace doesn't work running on Termux in Android

### ISSUE THREAD

**Issue by kveroneau** [lanurmi/efte#104]
So, I managed to get nefte to compile and run in Termux(a Linux environment for Android), it runs, but when I press Backspace on the Android keyboard it just shows a "^?" in the editor, which is what stty says is my backspace key...  Any ideas on how I can fix this?  This would be a great mobile editor for my phone if I could only get backspace to work correctly with the editor.

**Comment by kveroneau** [comment]
I am starting to suspect that this is related to Termux using the ncursesw library instead of ncurses, and nefte isn't coded correctly to work with wide-char/wide-string, and breaks when using backspace.  Other special keys seem to work fine, such as the arrow keys, and pressing ctrl-h performs a backspace.  So I'm not entirely sure it is related to wide-char vs regular char.  I'll scan through part of the nefte code where keyboard scanning is done later to see how backspace is determined.

**Comment by kveroneau** [comment]
This patch provided by the developer of Termux resolved the issue for me:  https://gist.github.com/its-pointless/15a5274eb6cc5106b691793912a8fc32

**Comment by lanurmi** [comment]
Thanks for looking into the problem, and providing a solution! I'm not familiar with Termux, nor am I familiar how nefte works internally – all I can say is that eFTE in general isn't really written with wide chars or Unicode in mind, so it doesn't surprise me if something doesn't work. The patch you provided seems trivial and harmless, so I'll apply it as soon as possible.
