### ISSUE TITLE
sprintf memory runoff at EBuffer::Redraw()

### ISSUE THREAD

**Issue by lanurmi** [lanurmi/efte#38]
When I was about to paste something to a buffer, it crashes with the backtrace given below. I reported the same problem as Ubuntu bug report \# 125315 awhile ago \( https://bugs.launchpad.net/ubuntu/+source/fte/+bug/125315 \). Please fix that on efte.

In efte source tree, the problem lies in routine EBuffer::Redraw\(\) -- here:

File: e\_redraw.cpp

461                  char num\[10\];
462  
463                  MoveStr\(B, 0, W-&gt;Cols, s, SColor, W-&gt;Cols\);
464                  sprintf\(num, " %s %d", CCharStr, ModelNo\);
465                  MoveStr\(B, W-&gt;Cols - strlen\(num\), W-&gt;Cols, num, SColor, W-&gt;Cols\);
466  

Increase "num\[10\]" to "num\[32\]" and it would stay away from the
problem. Of for safer programming, change sprintf to use snprintf.

Wirawan

Reported by: wirawan0

Original Ticket: [efte/bugs/37](https://sourceforge.net/p/efte/bugs/37)

**Comment by dmcbride** [comment]
looks like this was addressed in b11072d2

**Comment by lanurmi** [comment]
Indeed looks like it. Also looks like it was already fixed in efte months before this ticket was created. And never fixed in Ubuntu; surprise.
